sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-215259830466"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
